FROM ubuntu:24.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
	apt-get install -y gdb vim tmux git python3 python3-pip python3-setuptools file socat wget htop ltrace strace patchelf curl && \
	apt-get install -y build-essential libssl-dev libffi-dev

RUN wget -q -O- https://gef.blah.cat/sh | sh
RUN echo "set auto-load safe-path /" >> /root/.gdbinit

# RUN pip3 install --upgrade pip # for setuptools_rust

# RUN apt-get install -y python-capstone python-keystone

RUN cd /tmp/ && \
	git clone https://github.com/Gallopsled/pwntools && \
	cd pwntools/ && \
	git checkout dev && \
	pip3 install --break-system-packages --editable .

RUN wget https://raw.githubusercontent.com/hellman/fixenv/master/r.sh -O /usr/bin/fixenv && \
	chmod +x /usr/bin/fixenv


COPY ./ynetd /usr/bin/

# TODO: https://github.com/haampie/libtree


# apt-get -y install locales
# locale-gen en_US.UTF-8

ENV PYTHONIOENCODING=utf8
ENV LC_CTYPE=C.UTF-8
