.PHONY:
main: pwn18.04 pwn20.04 pwn21.04
.PHONY:
pwn18.04:
	docker build -t pwn18.04 -f Dockerfile-18.04 .

.PHONY:
pwn20.04:
	docker build -t pwn20.04 -f Dockerfile-20.04 .

.PHONY:
pwn21.04:
	docker build -t pwn21.04 -f Dockerfile-21.04 .
