[package]
authors = ["Mrmaxmeier <Mrmaxmeier@gmail.com>"]
name = "mdc"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.32.0"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.35"
url = "2.0"
reqwest = { version = "0.10.0", features = ["blocking", "json"] }
