[package]
authors = ["Mrmaxmeier <Mrmaxmeier@gmail.com>"]
name = "mdc"
version = "0.1.0"

[dependencies]
clap = "2.31.2"
hyper = "0.10"
serde = "1.0.62"
serde_derive = "1.0.62"
serde_json = "1.0.18"
url = "1.7.0"
