[package]
name = "mediad"
version = "0.1.0"
authors = ["Mrmaxmeier <Mrmaxmeier@gmail.com>"]

[dependencies]
iron = "^0.4.0"
router = "^0.2.0"
persistent = "^0.2.0"
mime = "^0.2.0"
urlencoded = "^0.4.0"
unix_socket = "^0.5.0"
rand = "^0.3.14"
libc = "^0.2.11"

serde = "*"
serde_json = "*"
serde_macros = "*"
