[package]
authors = ["Mrmaxmeier <Mrmaxmeier@gmail.com>"]
name = "mediad"
version = "0.1.0"
edition = "2018"

[dependencies]
libc = "0.2.46"
rand = "0.7.3"
rocket = "0.4.0"
rocket_contrib = "0.4.0"

serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.35"
unix_socket = "0.5.0"
