[package]
authors = ["Mrmaxmeier <Mrmaxmeier@gmail.com>"]
name = "mediad"
version = "0.1.0"

[dependencies]
libc = "^0.2.11"
rand = "^0.3.14"
rocket = "0.3.4"
rocket_codegen = "0.3.4"
rocket_contrib = "0.3.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
unix_socket = "^0.5.0"
