[package]
authors = ["Mrmaxmeier <Mrmaxmeier@gmail.com>"]
name = "mediad"
version = "0.1.0"

[dependencies]
iron = "0.5.1"
libc = "^0.2.11"
mime = "^0.2.0"
persistent = "0.3.0"
rand = "^0.3.14"
router = "0.5.1"
serde = "*"
serde_derive = "*"
serde_json = "*"
unix_socket = "^0.5.0"
urlencoded = "0.5.0"
