[package]
authors = ["Mrmaxmeier <Mrmaxmeier@gmail.com>"]
name = "lock"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.31.2"
libc = "0.2.41"
notify-rust = "4.5"
term = "0.7.0"
term_size = "0.3.1"
x11-dl = "2.17.5"

[dependencies.x11]
features = ["xlib", "xss"]
version = "2.17.5"
