[package]
name = "mdc"
version = "0.1.0"
authors = ["Mrmaxmeier <Mrmaxmeier@gmail.com>"]

[dependencies]
docopt = "^0.6.80"
docopt_macros = "^0.6.84"
rustc-serialize = "^0.3"
hyper = "^0.9.5"
url = "^1.1.0"
serde = "0.7.10"
serde_json = "0.7.1"
serde_macros = "*"
