[package]
authors = ["Mrmaxmeier <Mrmaxmeier@gmail.com>"]
name = "mdc"
version = "0.1.0"

[dependencies]
clap = "^2.24.1"
hyper = "^0.10.0"
serde = "^1.0.0"
serde_derive = "^1.0.0"
serde_json = "^1.0.0"
url = "^1.1.0"
